### ISSUE TITLE
Some schematic symbols are ridiculously wide

### ISSUE THREAD

**Issue by minexew** [esden/stm32-kicad-lib#2]
For example, this symbol for the tiny 28-pin STM32L031G6 doesn't fit into a landscape A4 schematic

![screenshot](https://imgur.com/7UdlWLZ.png)

**Comment by jrsa** [comment]
parts like this look a little silly to me, i would rather see just the pin name. I commented out the place in the generation script where the pin functions are added, which yields (to me) a much cleaner part:
![ss_ 2018-04-22 at 3 06 28 pm](https://user-images.githubusercontent.com/5141229/39100409-e9b46452-463e-11e8-8b78-5de8f45153ad.png)

**Comment by esden** [comment]
@jrsa  that is all a matter of preference. I like seeing all the functions of a pin in a schematic. It makes pin mapping easier. We already have two types of generated symbols, single units and multiple unit ones. For large parts multi-unit parts are better, and that address the first issue. For the second issue, if you want to add a third type of just the bare names to the generation script I will review it and merge it.

Unless you have good suggestions to address your personal preferences of how the symbols should look like without forcing it on everyone else I will close the issue.

**Comment by esden** [comment]
@minexew you should use the multiunit symbol version. The script currently generates symbols that are symmetric, this is why the symbol you show is that large. The left side contains a long string description of one of the pins making the other side equally large. This should not be the case with the multiunit symbol.

We can consider making the script generate non symmetric symbols to avoid making odd symbols like the one you pointed out.

**Comment by minexew** [comment]
IMO, listing out every possible function for each pin is a bad enough idea as of now, and it will only get worse as the devices become more versatile and their capabilities increase further.

I definitely prefer @jrsa 's solution of omitting the lists altogether. When designing the board, you will typically have the device datasheet open for most of the time, which includes a nice table of mapping options. (including other crucial information such as 5V tolerance, drive strength etc.)
One can also use the freeware STM32CubeMX to determine pinout, clocking and peripheral settings at the same time, as well as *validate* your overall configuration -- a schematic editor won't be able to help you with that, ever.

Adding a detailed tooltip to each pin would be great, but that's probably beyond kicad's capabilities.

Having to use multi-part symbols for a device with fewer than 32 pins is somewhat ridiculous.

**Comment by esden** [comment]
You are entiteled to have your opinion. Does not mean I have to make the library I shared here for free with an open license the way you want it. 😀 

I do not have time for this kind of arguments. If you want to contribute some additional types of symbols to the library you are welcome to open a pull request. I am happy to add more options of symbols to choose from. But I do not have to waste my time arguing what particular approach is the "right" one. I hope you understand... 😈

**Comment by minexew** [comment]
Absolutely. At the same time, I see nothing wrong in discussing the benefits and drawbacks of different approaches.

**Comment by jrsa** [comment]
command line switch in the script? very simple. also this is pretty much the point of making something open source, allowing other people to improve upon your work without the need for you to do any more work yourself! i will certainly create a cleaner version of my modification and open a PR, but it makes sense to get other users' input first no?

**Comment by jrsa** [comment]
actually, saw your comment above @esden and I will just add another type of part without the alternate functions appended to the pin name as in my picture

**Comment by yetihehe** [comment]
Needed this lib just yesterday but I don't like those long pin names too. Just added pull request with --short-pins option.

**Comment by esden** [comment]
We now have the `--short-pins` thanks to @yetihehe if that is what you prefer. The library in the repository still uses the full names with all the options as this is my preference, but now you can generate the symbols with the shorter names. Thus I consider this issue closed.
